# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - /feature\/.+/
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:5.7
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --explicit_defaults_for_timestamp=true --skip-character-set-client-handshake --character-set-filesystem=utf8
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      SPRING_PROFILES_ACTIVE: ci-test

    #command: [--character-set-server=utf8, --collation-server=utf8_unicode_ci, --explicit_defaults_for_timestamp=true, --skip-character-set-client-handshake, --character-set-filesystem=utf8]

    steps:
      - checkout
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

#      - run:
#          name: setup legacy library
#          command: mvn install:install-file -Dfile=legacyLibraries/kuromoji-0.7.7.jar -DgroupId=org.atilika.kuromoji -DartifactId=kuromoji -Dversion=0.7.7 -Dpackaging=jar -DgeneratePom=true
      - run:
          name: setup remote library
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run:
          name: db migration
          command: mvn flyway:migrate -Dflyway.user=root -Dflyway.password="" -Dflyway.url=jdbc:mysql://localhost:3306/circle_test -Dflyway.driver=com.mysql.jdbc.Driver -Dflyway.placeholderReplacement=false
      - run:
          name: test
          command: mvn clean test
#          command: mvn clean clover:setup test clover:aggregate clover:clover
#      - store_artifacts:
#          path: target/site/clover
#
